name: sqfentity
homepage: https://github.com/qijie07/sqf_entity
description: SqfEntity ORM for Flutter/Dart lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework.
author:  Wyatt <storykym@gmail.com>
version: 2.3.1+7
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_sqlcipher: 3.2.0
  sqfentity_gen: 2.5.0
  synchronized: 3.4.0
  path: 1.9.1
  sqflite_common: 2.5.5
  sqflite_common_ffi: 2.3.6

dependency_overrides:
  sqfentity_gen:
    git:
      url: https://github.com/chameleon-smarthome/sqfentity_gen.git
      ref: test2
